name: Cpress Tests
on: [push]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        uses: cypress-io/github-action@v4
        with: 
          command: npm cypress install
      - name: test
        run: 
          npx cypress run