name: Unit Tests
on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        working-directory: server
        run: 
          npm install
      - name: test
        working-directory: server
        run: 
          npm test
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        run: 
          npm install
      - name: install cypress
        run: 
          npm install cypress
      - name: test
        run: 
          npm cypress run
