name: Unit Tests
on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        working-directory: server
        run: npm install
        run: npm test
